package hsr.core.equipment;

public enum RelicSet {
    BAND_OF_SIZZLING_THUNDER,
    BELOBOG_OF_THE_ARCHITECTS,
    CELESTIAL_DIFFERENTIATOR,
    CHAMPION_OF_STREETWISE_BOXING,
    EAGLE_OF_TWILIGHT_LANE,
    FLAMESMITH_OF_LAVA_FORGING,
    FLEET_OF_THE_AGELESS,
    GENIUS_OF_BRILLIANT_STARS,
    GUARD_OF_WUTHERING_SNOW,
    HUNTER_OF_GLACIAL_FOREST,
    INERT_SALSOTTO,
    KNIGHT_OF_PURITY_PALACE,
    MUSKETEER_OF_WILD_WHEAT,
    PAN_GALACTIC_COMMERCIAL_INTERPRISE,
    PASSERBY_OF_WANDERING_CLOUD,
    SPACE_SEALING_STATION,
    SPRIGHTLY_VONWACQ,
    TALIA_KINGDOM_OF_BANDITRY,
    THIEF_OF_SHOOTING_METEOR,
    WASTELANDER_OF_BANDITRY_DESERT
}
