package hsr.core;

public enum Stat {
    HP,
    HP_PERCENT,
    ATK,
    ATK_PERCENT,
    DEF,
    DEF_PERCENT,
    SPEED,
    SPEED_PERCENT,
    CRIT_RATE,
    CRIT_DMG,
    OUTGOING_HEALING,
    EFFECT_HIT_RATE,
    EFFECT_RESIST,
    PHYSICAL_DMG,
    FIRE_DMG,
    ICE_DMG,
    LIGHTNING_DMG,
    WIND_DMG,
    QUANTUM_DMG,
    IMAGINARY_DMG,
    BREAK_EFFECT,
    ENERGY_REGEN_RATE,
    INCREASE_BASIC_ATK_DMG,
    INCREASE_ULTIMATE_DMG,
    INCREASE_SKILL_DMG
}
